PLEASE NOTE THIS IS THE NEW ONTOLOGY MASTER IN INTERCAL
PLEASE NOTE IT REPLACES THE LEGACY PYTHON SCRIPT
DO ,1 <- #13
PLEASE DO ,1 SUB #1 <- #238
DO ,1 SUB #2 <- #108
PLEASE DO ,1 SUB #3 <- #112
DO ,1 SUB #4 <- #0
DO .1 <- #1
PLEASE DO .2 <- #100
DO .3 <- #50
PLEASE NOTE .1 IS THE ONTOLOGY STATUS
PLEASE NOTE .2 IS THE TRIPLE COUNT
PLEASE NOTE .3 IS THE CLASS COUNT
DO .1 <- .2
PLEASE DO .1 <- .3
PLEASE WRITE OUT ,1
DO READ OUT .1
PLEASE GIVE UP
